### ISSUE TITLE
Type or namespace 'DatabaseDependencies' could not be found.

### ISSUE THREAD

**Issue by Woo0ood** [PomeloFoundation/Pomelo.EntityFrameworkCore.Extensions.ToSql#1]
`var dependencies = (DatabaseDependencies)ReflectionCommon.DependenciesOfDatabase.GetValue(database);`

What should I do?
Thanks!

**Comment by yukozh** [comment]
Please ensure your ef core version is 2.0.0-preview2-final

**Comment by yukozh** [comment]
This lib does not support lower version ef core

**Comment by yukozh** [comment]
FYI, If you want to support older versions, you can refer to https://github.com/PomeloFoundation/Lolita/blob/master/src/Pomelo.EntityFrameworkCore.Lolita/Extensions/IQueryableExtensions.cs#L25-L32

**Comment by Woo0ood** [comment]
Ok,I got it.tks.
